FROM python:3.8

ENV ftp_proxy http://proxy.cse.cuhk.edu.hk:8000
ENV http_proxy http://proxy.cse.cuhk.edu.hk:8000
ENV https_proxy http://proxy.cse.cuhk.edu.hk:8000

RUN pip install pip-tools

COPY ./requirements.txt .
COPY ./requirements-dev.txt .
RUN pip-sync requirements.txt requirements-dev.txt

WORKDIR /usr/src/app

COPY dockerfile_django_dev_entrypoint.sh /dockerfile_django_dev_entrypoint.sh
RUN chmod 755 /dockerfile_django_dev_entrypoint.sh
ENTRYPOINT ["/dockerfile_django_dev_entrypoint.sh"]
