FROM python:3.8

ENV ftp_proxy http://proxy.cse.cuhk.edu.hk:8000
ENV http_proxy http://proxy.cse.cuhk.edu.hk:8000
ENV https_proxy http://proxy.cse.cuhk.edu.hk:8000

RUN wget https://get.docker.com -q -O /tmp/getdocker && \
    chmod +x /tmp/getdocker && \
    sh /tmp/getdocker

RUN pip install pip-tools

COPY ./requirements.txt .
RUN pip-sync requirements.txt

WORKDIR /usr/src/app
